### ISSUE TITLE
ValueError: TensorIntrin 'm16n8k8_init' is not registered

### ISSUE THREAD

**Issue by twmht** [cblmemo/TVMGemmAsync#1]
Hi,

i want to run the benchmark in https://github.com/cblmemo/TVMGemmAsync/tree/main/mma,

but got 

```
ValueError: TensorIntrin 'm16n8k8_init' is not registered
```

Can you tell me which tvm commit you were on?

**Comment by cblmemo** [comment]
The benchmark script uses some deprecated intrin names. I just pushed an updated version and it should work in the latest main branch now 🙂 Could you give it another try?

**Comment by twmht** [comment]
@cblmemo 

appreciated. 

I am a newbie and learning TVM workflow now, and i think writing a scheduler for tensorcore is  a good start point.

btw, can you help to check this issue(https://github.com/apache/tvm/issues/15426)? I am not sure if i am using tensorcore wrong and I don't have any idea about what is SSR loops.
